description: "Portable shared pre-commit hook suites and safe materializer."
plugins:
    - "jekyll-sitemap"
    - "jekyll-seo-tag"
    - "jekyll-paginate"
    - "jekyll-feed"
    - "jekyll-archives"
    - "jekyll-language-plugin"
    - "jekyll-algolia"
    - "jekyll-mentions"
    - "jekyll-admin"
    - "jekyll-loading-lazy"
remote_theme: "pages-themes/hacker@v0.2.0"
title: "Pre-commit Config Nick2bad4u"
url: "https://nick2bad4u.github.io/pre-commit-config-nick2bad4u" # the base hostname & protocol for your site
